name: flutter_template
description: "Flutter 项目模板，整合常用功能和开发实践"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # GetX 框架 https://pub.dev/packages/get
  get: ^4.7.2

  # 屏幕适配工具 https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^5.9.3

  # Widget 样式化工具 https://pub.dev/packages/styled_widget
  styled_widget: ^0.4.1

  # 网络请求库 https://pub.dev/packages/dio
  dio: ^5.8.0+1

  # JSON 序列化工具类库 https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0

  # Retrofit 网络请求库 https://pub.dev/packages/retrofit
  retrofit: ^4.4.2

  # svg框架 https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.1.0

  # 持久化存储库 https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.5.3

  # 下拉刷新 上拉加载 https://pub.dev/packages/easy_refresh
  easy_refresh: ^3.4.0

  # 页面动画 https://pub.dev/packages/animations
  animations: ^2.0.11

  # 加载弹窗 和 Toast https://pub.dev/packages/bot_toast
  bot_toast: ^4.1.3

  # 应用内更新 https://pub.dev/packages/upgrader
  upgrader: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Flutter 代码风格检查 https://pub.dev/packages/flutter_lints
  flutter_lints: ^5.0.0

  # 网络请求通知栏拦截器 https://pub.dev/packages/alice/versions/1.0.0-dev.12
  # 文档 https://jhomlala.github.io/alice/#/README
  alice: ^1.0.0-dev.12
  alice_dio: ^1.0.6

  # JSON 序列化工具 https://pub.dev/packages/json_serializable
  json_serializable: ^6.9.5

  # Retrofit 代码生成库 https://pub.dev/packages/retrofit_generator
  retrofit_generator: ^9.1.9

  # 构建工具 https://pub.dev/packages/build_runner
  build_runner: ^2.4.15

  # dio网络请求日志工具 https://pub.dev/packages/pretty_dio_logger
  pretty_dio_logger: ^1.4.0

  # 日志记录工具 https://pub.dev/packages/logger
  logger: ^2.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/
    - assets/json/
    - assets/appcast.xml # 应用更新配置
#    - assets/theme/ 开发时的主题配置 不打包到生产
#    - assets/dev/ # 开发模式下的资源 比如生成启动页 不打包到生产

dependency_overrides:
  image_picker: 1.1.2
